# dependabot.yml file with
# customized nuget configuration

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/FluentTableView"
    target-branch: "develop"
    schedule:
      interval: "daily"
